// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.1-0.20240601101045-cb61b77eea50 DO NOT EDIT.
package openapi

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ErrorResponseSchema defines model for ErrorResponseSchema.
type ErrorResponseSchema struct {
	Message string `json:"message"`
}

// TodoSchema defines model for TodoSchema.
type TodoSchema struct {
	Completed bool               `json:"completed"`
	Id        openapi_types.UUID `json:"id"`
	Title     string             `json:"title"`
}

// CreateTodoJSONBody defines parameters for CreateTodo.
type CreateTodoJSONBody struct {
	Title string `json:"title"`
}

// UpdateTodoJSONBody defines parameters for UpdateTodo.
type UpdateTodoJSONBody struct {
	Completed bool   `json:"completed"`
	Title     string `json:"title"`
}

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody CreateTodoJSONBody

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody UpdateTodoJSONBody
